version: '3.8'
services:
  customer_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-transaction-service
    restart: always
    ports:
      - 8092:8092
    networks:
      network_bank:
        aliases:
          - net_cloud
networks:
  network_bank:
    name: net_cloud
    external: true